### PR TITLE
#262 - removed extra year-round class

### LINKED ISSUE #262: Remove pink outline on Year Round schools
Since we're including the calendar type in the profile, can we remove the pink outline on the map for year-round schools? It's confusing along with all the other colors, and am not sure it's important enough to warrant inclusion on the map view.

### PR DESCRIPTION
**Pull request by elynch**
Fixes #262

### CODE REVIEW

**Comment by victor-rocha** [comment]
is this class not used at all? I thought we were using it to display the YR letters for school icon.

**Comment by elynch** [comment]
This class is no longer in use since we are using the "Year Round Option" label instead.

**Comment by jtf621** [comment]
+1 looks good @elynch

**Comment by jtf621** [comment]
Tested locally, looks good.  Merged.  Thanks @elynch

**Pull request merged**
